### PR TITLE
Introduce document website

### PR DESCRIPTION
**Pull request by gengliangwang**
Framework: https://squidfunk.github.io/mkdocs-material/
To install: pip install mkdocs-material
To Run it:  mkdocs serve 

The content is similar to README.md. In additional, it shows the method APIs so that users are more clear about how to use them.

### CODE REVIEW

**Comment by MrPowers** [comment]
LGTM.  I will make edits when it's published, but this is a great first pass!

**Comment by dennyglee** [comment]
LGTM!

**Review by allisonwang-db — APPROVED** [review]
Great!

**Comment by gengliangwang** [comment]
@MrPowers @dennyglee Thanks for the reviews!

**Pull request merged**
