### PR TITLE
Move spark related methods to SparkUtils

### LINKED ISSUE #108: Move all spark related methods to a new class SparkUtils
Create a new class for all the utility method related to Spark, for example, `_get_dataframe_results`, `_get_df_schema`, etc.
The refactoring can simplify the code in `pyspark_ai.py`.

### PR DESCRIPTION
**Pull request by SemyonSinchenko**
Sorry for the delay with it, I was on vacation :)

Close #108

### CODE REVIEW

**Comment by SemyonSinchenko** [comment]
I'll try to understand what is the problem with tests.

**Comment by SemyonSinchenko** [comment]
@gengliangwang May you help me here? I see that `BaseLanguageModel` is still [used](https://github.com/pyspark-ai/pyspark-ai/blob/master/tests/test_spark_ai.py#L18), but from documentation of `langchain` I see that class hierarchy is the following:
image
So, for me it is a bug, because in [spark_sql_chain.py](https://github.com/pyspark-ai/pyspark-ai/blob/master/pyspark_ai/spark_sql_chain.py#L32) you are expecting the instance of `BaseChatModel`

Also, from the source of `langchain` I see that `BaseLanguageModel` is deprecated:
```
"""Deprecated module for BaseLanguageModel class, kept for backwards compatibility."""
```

Should I change this line `cls.llm_mock = MagicMock(spec=BaseLanguageModel)` to `cls.llm_mock = MagicMock(spec=BaseChatModel)` in `test_spark_ai.py`?

**Comment by gengliangwang** [comment]
@SemyonSinchenko welcome back!
I am on vacation this week but I might still check github at evening

**Comment by gengliangwang** [comment]
> Should I change this line cls.llm_mock = MagicMock(spec=BaseLanguageModel) to cls.llm_mock = MagicMock(spec=BaseChatModel) in test_spark_ai.py?


Yes, sounds good. We start the project on June and there are many refactors on langchain since then

**Comment by SemyonSinchenko** [comment]
@gengliangwang Sorry for tagging, but I'm out of ideas. This `llmchain` looks broken somehow for me. This assert [here](https://github.com/pyspark-ai/pyspark-ai/blob/master/pyspark_ai/spark_sql_chain.py#L32)
```python
        assert isinstance(
            self.llm, BaseChatModel
        ), f"The llm is not an instance of BaseChatModel"
```
looks impossible to pass via `MagicMock`.

The minimal reproducible example:
image

**Comment by gengliangwang** [comment]
@SemyonSinchenko I don't quite get it. How does the refactoring cause a test issue here.

**Comment by SemyonSinchenko** [comment]
> @SemyonSinchenko I don't quite get it. How does the refactoring cause a test issue here.

I do not understand it too. The same problem with test is also [here](https://github.com/pyspark-ai/pyspark-ai/pull/177), where I did not ever touch the code, only pipeline...

**Comment by gengliangwang** [comment]
@asl3 could you help take a look at the failure here? I think we need to create a dummy BaseChatModel for testing, instead of a mock one.

**Comment by SemyonSinchenko** [comment]
@gengliangwang I see that there is a [FakeLLM](https://python.langchain.com/docs/modules/model_io/models/llms/fake_llm) class in `langchain`. May I try to use it instead of `unittest.mock.MagickMock`?

**Comment by gengliangwang** [comment]
> @gengliangwang I see that there is a [FakeLLM](https://python.langchain.com/docs/modules/model_io/models/llms/fake_llm) class in langchain. May I try to use it instead of unittest.mock.MagickMock?

It's not a BaseChatModel. So probably it won't work

**Pull request closed without merging**
